/**
 * @file Diagonal.h
This attribute is part of the possible options for the trace splom.

This file has been autogenerated from the official plotly.js source.

If you like Plotly, please support them: L<https://plot.ly/> 
Open source announcement: L<https://plot.ly/javascript/open-source-announcement/>

Full reference: L<https://plot.ly/javascript/reference/#splom>

DISCLAIMER

This is an unofficial Plotly Perl module. Currently I'm not affiliated in any way with Plotly. 
But I think plotly.js is a great library and I want to use it with C++.

*/

#include <vector>
#include <string>
#include <sstream>

#include <json11.hpp>




namespace CppPlotly {
    namespace Trace {
    namespace splom {

    /**
     * 
     *
     *
     */
    class Diagonal {
    public:

    /**
Determines whether or not subplots on the diagonal are displayed.
*/Diagonal & Visible(const bool &visible ) {
    _diagonal.insert({"visible", visible});
    return *this;
}




    json11::Json to_json() const {
        return _diagonal;
    }

    private:

    json11::Json::object _diagonal;

    };

    }

    }
}
