/**
 * @file Histogram2dcontour.h
This file has been autogenerated from the official plotly.js source.

If you like Plotly, please support them: L<https://plot.ly/> 
Open source announcement: L<https://plot.ly/javascript/open-source-announcement/>

Full reference: L<https://plot.ly/javascript/reference/#histogram2dcontour>

This is an unofficial Plotly Perl module. Currently I'm not affiliated in any way with Plotly. 
But I think plotly.js is a great library and I want to use it with C++.
 *
 */
#include <vector>
#include <string>
#include <sstream>

#include <json11.hpp>

#include "../BaseTrace.h"

#include "CppPlotly/Trace/Histogram2dcontour/Colorbar.h"
#include "CppPlotly/Trace/Histogram2dcontour/Contours.h"
#include "CppPlotly/Trace/Histogram2dcontour/Hoverlabel.h"
#include "CppPlotly/Trace/Histogram2dcontour/Line.h"
#include "CppPlotly/Trace/Histogram2dcontour/Marker.h"
#include "CppPlotly/Trace/Histogram2dcontour/Stream.h"
#include "CppPlotly/Trace/Histogram2dcontour/Transform.h"
#include "CppPlotly/Trace/Histogram2dcontour/Xbins.h"
#include "CppPlotly/Trace/Histogram2dcontour/Ybins.h"


namespace CppPlotly {
    namespace Trace {
        /**
         * The sample data from which statistics are computed is set in `x` and `y` (where `x` and `y` represent marginal distributions, binning is set in `xbins` and `ybins` in this case) or `z` (where `z` represent the 2D distribution and binning set, binning is set by `x` and `y` in this case). The resulting distribution is visualized as a contour plot.
         *
         *
         */ 
        class Histogram2dcontour : public virtual CppPlotly::BaseTrace {
        public:
            Histogram2dcontour() :
                            _histogram2dcontour({
                                {"type", "histogram2dcontour"},
                                    })
                        {}

           /**
Determines whether or not the x axis bin attributes are picked by an algorithm. Note that this should be set to false if you want to manually set the number of bins using the attributes in xbins.
*/Histogram2dcontour & Autobinx(const bool &autobinx ) {
    _histogram2dcontour.insert({"autobinx", autobinx});
    return *this;
}


/**
Determines whether or not the y axis bin attributes are picked by an algorithm. Note that this should be set to false if you want to manually set the number of bins using the attributes in ybins.
*/Histogram2dcontour & Autobiny(const bool &autobiny ) {
    _histogram2dcontour.insert({"autobiny", autobiny});
    return *this;
}


/**
Determines whether or not the colorscale is picked using the sign of the input z values.
*/Histogram2dcontour & Autocolorscale(const bool &autocolorscale ) {
    _histogram2dcontour.insert({"autocolorscale", autocolorscale});
    return *this;
}


/**
Determines whether or not the contour level attributes are picked by an algorithm. If *true*, the number of contour levels can be set in `ncontours`. If *false*, set the contour level attributes in `contours`.
*/Histogram2dcontour & Autocontour(const bool &autocontour ) {
    _histogram2dcontour.insert({"autocontour", autocontour});
    return *this;
}


Histogram2dcontour & Colorbar(const CppPlotly::Trace::histogram2dcontour::Colorbar &colorbar ) {
    _histogram2dcontour.insert({"colorbar", colorbar});
    return *this;
}


/**
Sets the colorscale. The colorscale must be an array containing arrays mapping a normalized value to an rgb, rgba, hex, hsl, hsv, or named color string. At minimum, a mapping for the lowest (0) and highest (1) values are required. For example, `[[0, 'rgb(0,0,255)', [1, 'rgb(255,0,0)']]`. To control the bounds of the colorscale in z space, use zmin and zmax
*/Histogram2dcontour & Colorscale(const json11::Json::object &colorscale ) {
    _histogram2dcontour.insert({"colorscale", colorscale});
    return *this;
}


Histogram2dcontour & Contours(const CppPlotly::Trace::histogram2dcontour::Contours &contours ) {
    _histogram2dcontour.insert({"contours", contours});
    return *this;
}


/**
Assigns extra data each datum. This may be useful when listening to hover, click and selection events. Note that, *scatter* traces also appends customdata items in the markers DOM elements
*/Histogram2dcontour & Customdata(const std::vector<double> &customdata ) {
    _histogram2dcontour.insert({"customdata", customdata});
    return *this;
}


/**
Assigns extra data each datum. This may be useful when listening to hover, click and selection events. Note that, *scatter* traces also appends customdata items in the markers DOM elements
*/Histogram2dcontour & Customdata(const std::vector<std::string> &customdata ) {
    _histogram2dcontour.insert({"customdata", customdata});
    return *this;
}


/**
Assigns extra data each datum. This may be useful when listening to hover, click and selection events. Note that, *scatter* traces also appends customdata items in the markers DOM elements
*/Histogram2dcontour & Customdata(const json11::Json::object &customdata ) {
    _histogram2dcontour.insert({"customdata", customdata});
    return *this;
}


/**
Sets the source reference on plot.ly for  customdata .
*/Histogram2dcontour & Customdatasrc(const std::string &customdatasrc ) {
    _histogram2dcontour.insert({"customdatasrc", customdatasrc});
    return *this;
}


/**
Specifies the binning function used for this histogram trace. If *count*, the histogram values are computed by counting the number of values lying inside each bin. If *sum*, *avg*, *min*, *max*, the histogram values are computed using the sum, the average, the minimum or the maximum of the values lying inside each bin respectively.
*/Histogram2dcontour & Histfunc(const json11::Json::object &histfunc ) {
    _histogram2dcontour.insert({"histfunc", histfunc});
    return *this;
}


/**
Specifies the type of normalization used for this histogram trace. If **, the span of each bar corresponds to the number of occurrences (i.e. the number of data points lying inside the bins). If *percent* / *probability*, the span of each bar corresponds to the percentage / fraction of occurrences with respect to the total number of sample points (here, the sum of all bin HEIGHTS equals 100% / 1). If *density*, the span of each bar corresponds to the number of occurrences in a bin divided by the size of the bin interval (here, the sum of all bin AREAS equals the total number of sample points). If *probability density*, the area of each bar corresponds to the probability that an event will fall into the corresponding bin (here, the sum of all bin AREAS equals 1).
*/Histogram2dcontour & Histnorm(const json11::Json::object &histnorm ) {
    _histogram2dcontour.insert({"histnorm", histnorm});
    return *this;
}


/**
Determines which trace information appear on hover. If `none` or `skip` are set, no information is displayed upon hovering. But, if `none` is set, click and hover events are still fired.
*/Histogram2dcontour & Hoverinfo(const json11::Json::object &hoverinfo ) {
    _histogram2dcontour.insert({"hoverinfo", hoverinfo});
    return *this;
}


/**
Sets the source reference on plot.ly for  hoverinfo .
*/Histogram2dcontour & Hoverinfosrc(const std::string &hoverinfosrc ) {
    _histogram2dcontour.insert({"hoverinfosrc", hoverinfosrc});
    return *this;
}


Histogram2dcontour & Hoverlabel(const CppPlotly::Trace::histogram2dcontour::Hoverlabel &hoverlabel ) {
    _histogram2dcontour.insert({"hoverlabel", hoverlabel});
    return *this;
}


/**
Assigns id labels to each datum. These ids for object constancy of data points during animation. Should be an array of strings, not numbers or any other type.
*/Histogram2dcontour & Ids(const std::vector<double> &ids ) {
    _histogram2dcontour.insert({"ids", ids});
    return *this;
}


/**
Assigns id labels to each datum. These ids for object constancy of data points during animation. Should be an array of strings, not numbers or any other type.
*/Histogram2dcontour & Ids(const std::vector<std::string> &ids ) {
    _histogram2dcontour.insert({"ids", ids});
    return *this;
}


/**
Assigns id labels to each datum. These ids for object constancy of data points during animation. Should be an array of strings, not numbers or any other type.
*/Histogram2dcontour & Ids(const json11::Json::object &ids ) {
    _histogram2dcontour.insert({"ids", ids});
    return *this;
}


/**
Sets the source reference on plot.ly for  ids .
*/Histogram2dcontour & Idssrc(const std::string &idssrc ) {
    _histogram2dcontour.insert({"idssrc", idssrc});
    return *this;
}


/**
Sets the legend group for this trace. Traces part of the same legend group hide/show at the same time when toggling legend items.
*/Histogram2dcontour & Legendgroup(const std::string &legendgroup ) {
    _histogram2dcontour.insert({"legendgroup", legendgroup});
    return *this;
}


Histogram2dcontour & Line(const CppPlotly::Trace::histogram2dcontour::Line &line ) {
    _histogram2dcontour.insert({"line", line});
    return *this;
}


Histogram2dcontour & Marker(const CppPlotly::Trace::histogram2dcontour::Marker &marker ) {
    _histogram2dcontour.insert({"marker", marker});
    return *this;
}


/**
Sets the trace name. The trace name appear as the legend item and on hover.
*/Histogram2dcontour & Name(const std::string &name ) {
    _histogram2dcontour.insert({"name", name});
    return *this;
}


/**
Specifies the maximum number of desired bins. This value will be used in an algorithm that will decide the optimal bin size such that the histogram best visualizes the distribution of the data.
*/Histogram2dcontour & Nbinsx(const int &nbinsx ) {
    _histogram2dcontour.insert({"nbinsx", nbinsx});
    return *this;
}


/**
Specifies the maximum number of desired bins. This value will be used in an algorithm that will decide the optimal bin size such that the histogram best visualizes the distribution of the data.
*/Histogram2dcontour & Nbinsy(const int &nbinsy ) {
    _histogram2dcontour.insert({"nbinsy", nbinsy});
    return *this;
}


/**
Sets the maximum number of contour levels. The actual number of contours will be chosen automatically to be less than or equal to the value of `ncontours`. Has an effect only if `autocontour` is *true* or if `contours.size` is missing.
*/Histogram2dcontour & Ncontours(const int &ncontours ) {
    _histogram2dcontour.insert({"ncontours", ncontours});
    return *this;
}


/**
Sets the opacity of the trace.
*/Histogram2dcontour & Opacity(const double &opacity ) {
    _histogram2dcontour.insert({"opacity", opacity});
    return *this;
}


/**
Reverses the colorscale.
*/Histogram2dcontour & Reversescale(const bool &reversescale ) {
    _histogram2dcontour.insert({"reversescale", reversescale});
    return *this;
}


/**
Array containing integer indices of selected points. Has an effect only for traces that support selections. Note that an empty array means an empty selection where the `unselected` are turned on for all points, whereas, any other non-array values means no selection all where the `selected` and `unselected` styles have no effect.
*/Histogram2dcontour & Selectedpoints(const json11::Json::object &selectedpoints ) {
    _histogram2dcontour.insert({"selectedpoints", selectedpoints});
    return *this;
}


/**
Determines whether or not an item corresponding to this trace is shown in the legend.
*/Histogram2dcontour & Showlegend(const bool &showlegend ) {
    _histogram2dcontour.insert({"showlegend", showlegend});
    return *this;
}


/**
Determines whether or not a colorbar is displayed for this trace.
*/Histogram2dcontour & Showscale(const bool &showscale ) {
    _histogram2dcontour.insert({"showscale", showscale});
    return *this;
}


Histogram2dcontour & Stream(const CppPlotly::Trace::histogram2dcontour::Stream &stream ) {
    _histogram2dcontour.insert({"stream", stream});
    return *this;
}


Histogram2dcontour & Transforms(const std::vector<CppPlotly::Trace::histogram2dcontour::Transform> &transforms ) {
    _histogram2dcontour.insert({"transforms", transforms});
    return *this;
}


Histogram2dcontour & Uid(const std::string &uid ) {
    _histogram2dcontour.insert({"uid", uid});
    return *this;
}


/**
Determines whether or not this trace is visible. If *legendonly*, the trace is not drawn, but can appear as a legend item (provided that the legend itself is visible).
*/Histogram2dcontour & Visible(const json11::Json::object &visible ) {
    _histogram2dcontour.insert({"visible", visible});
    return *this;
}


/**
Sets the sample data to be binned on the x axis.
*/Histogram2dcontour & X(const std::vector<double> &x ) {
    _histogram2dcontour.insert({"x", x});
    return *this;
}


/**
Sets the sample data to be binned on the x axis.
*/Histogram2dcontour & X(const std::vector<std::string> &x ) {
    _histogram2dcontour.insert({"x", x});
    return *this;
}


/**
Sets the sample data to be binned on the x axis.
*/Histogram2dcontour & X(const json11::Json::object &x ) {
    _histogram2dcontour.insert({"x", x});
    return *this;
}


/**
Sets a reference between this trace's x coordinates and a 2D cartesian x axis. If *x* (the default value), the x coordinates refer to `layout.xaxis`. If *x2*, the x coordinates refer to `layout.xaxis2`, and so on.
*/Histogram2dcontour & Xaxis(const json11::Json::object &xaxis ) {
    _histogram2dcontour.insert({"xaxis", xaxis});
    return *this;
}


Histogram2dcontour & Xbins(const CppPlotly::Trace::histogram2dcontour::Xbins &xbins ) {
    _histogram2dcontour.insert({"xbins", xbins});
    return *this;
}


/**
Sets the calendar system to use with `x` date data.
*/Histogram2dcontour & Xcalendar(const json11::Json::object &xcalendar ) {
    _histogram2dcontour.insert({"xcalendar", xcalendar});
    return *this;
}


/**
Sets the source reference on plot.ly for  x .
*/Histogram2dcontour & Xsrc(const std::string &xsrc ) {
    _histogram2dcontour.insert({"xsrc", xsrc});
    return *this;
}


/**
Sets the sample data to be binned on the y axis.
*/Histogram2dcontour & Y(const std::vector<double> &y ) {
    _histogram2dcontour.insert({"y", y});
    return *this;
}


/**
Sets the sample data to be binned on the y axis.
*/Histogram2dcontour & Y(const std::vector<std::string> &y ) {
    _histogram2dcontour.insert({"y", y});
    return *this;
}


/**
Sets the sample data to be binned on the y axis.
*/Histogram2dcontour & Y(const json11::Json::object &y ) {
    _histogram2dcontour.insert({"y", y});
    return *this;
}


/**
Sets a reference between this trace's y coordinates and a 2D cartesian y axis. If *y* (the default value), the y coordinates refer to `layout.yaxis`. If *y2*, the y coordinates refer to `layout.yaxis2`, and so on.
*/Histogram2dcontour & Yaxis(const json11::Json::object &yaxis ) {
    _histogram2dcontour.insert({"yaxis", yaxis});
    return *this;
}


Histogram2dcontour & Ybins(const CppPlotly::Trace::histogram2dcontour::Ybins &ybins ) {
    _histogram2dcontour.insert({"ybins", ybins});
    return *this;
}


/**
Sets the calendar system to use with `y` date data.
*/Histogram2dcontour & Ycalendar(const json11::Json::object &ycalendar ) {
    _histogram2dcontour.insert({"ycalendar", ycalendar});
    return *this;
}


/**
Sets the source reference on plot.ly for  y .
*/Histogram2dcontour & Ysrc(const std::string &ysrc ) {
    _histogram2dcontour.insert({"ysrc", ysrc});
    return *this;
}


/**
Sets the aggregation data.
*/Histogram2dcontour & Z(const std::vector<double> &z ) {
    _histogram2dcontour.insert({"z", z});
    return *this;
}


/**
Sets the aggregation data.
*/Histogram2dcontour & Z(const std::vector<std::string> &z ) {
    _histogram2dcontour.insert({"z", z});
    return *this;
}


/**
Sets the aggregation data.
*/Histogram2dcontour & Z(const json11::Json::object &z ) {
    _histogram2dcontour.insert({"z", z});
    return *this;
}


/**
Determines the whether or not the color domain is computed with respect to the input data.
*/Histogram2dcontour & Zauto(const bool &zauto ) {
    _histogram2dcontour.insert({"zauto", zauto});
    return *this;
}


/**
Sets the hover text formatting rule using d3 formatting mini-languages which are very similar to those in Python. See: https://github.com/d3/d3-format/blob/master/README.md#locale_format
*/Histogram2dcontour & Zhoverformat(const std::string &zhoverformat ) {
    _histogram2dcontour.insert({"zhoverformat", zhoverformat});
    return *this;
}


/**
Sets the upper bound of color domain.
*/Histogram2dcontour & Zmax(const double &zmax ) {
    _histogram2dcontour.insert({"zmax", zmax});
    return *this;
}


/**
Sets the lower bound of color domain.
*/Histogram2dcontour & Zmin(const double &zmin ) {
    _histogram2dcontour.insert({"zmin", zmin});
    return *this;
}


/**
Sets the source reference on plot.ly for  z .
*/Histogram2dcontour & Zsrc(const std::string &zsrc ) {
    _histogram2dcontour.insert({"zsrc", zsrc});
    return *this;
}


 

            virtual json11::Json to_json() const {
                return _histogram2dcontour;
            }

        private:
            
            json11::Json::object _histogram2dcontour;

        };
    }
}


